### ISSUE TITLE
How is a tag removed from a contact?

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [GetResponse/sdk-php#13]
How do I remove a tag from a contact?

**Comment by maciejtarnowski** [comment]
Using UpdateContact operation. Both `tags` and `customFieldValues` behave as a _replace_, so all you have to do is [get the contact details](https://apireference.getresponse.com/#operation/getContactById), remove the tag (or tags) you want to unassign from the `tags` array and [update the contact](https://apireference.getresponse.com/#operation/updateContact). All "update" operations work the same - you can send just the fields you want to change, so you can pass only the `tags` field to the request body and it'll work fine.

Let me know, if you need more details.

**Comment by maciejtarnowski** [comment]
I'm closing the issue for now, please let me know if you need any more info and I'll be happy to reopen it for you.

**Comment by picocodes** [comment]
It wouldn't hurt to have an API endpoint that removes tags. Having to query a contact ID by email, then using the ID to fetch their current tags, and finally updating the tags puts a lot of stress on both our and your servers.
