### ISSUE TITLE
Some bugs with GetresponseClient

### ISSUE THREAD

**Issue by YaroslavMolchan** [GetResponse/sdk-php#19]
1. Sometimes when update contact via `GetresponseClient::call` and call `$response->isSuccess()` - got response `false`, but your Support team said that response was `true`.

2. Maybe related to bug above, maybe not, when I got `$response->isSuccess() === false`, I try to got response status code via `$response->getResponse()->getStatusCode()` and sometimes I got exception `Call to a member function getStatusCode() on null`, and now I need check for `getResponse` and then for `getStatusCode`, can you check this on your side?

**Comment by maciejtarnowski** [comment]
Hi @YaroslavMolchan,

I was informed that you've been already answered by one of our Account Managers, but here they are:

1. We've found your requests in the logs and they were successful, so we are not 100% sure what happened. If you didn't retry them, it might indicate some kind of a network problem. A network disruption would also explain the other issue.
2. Most probably, you didn't get an HTTP response here. As mentioned, there could have been a timeout, for example. You can see that there won't be a `$response` if the client throws an exception (and non-200 response **is not** an exception): https://github.com/GetResponse/sdk-php-client/blob/master/src/Operation/FailedOperationResponse.php#L50

If you have any further questions, please let us know.
