### ISSUE TITLE
Example of creating a new contact with tags

### ISSUE THREAD

**Issue by templeman** [GetResponse/sdk-php#6]
It's not clear from the documentation how to go about creating a new contact with tag attributes.

Based on [this example](https://github.com/GetResponse/sdk-php/blob/5894d9ffb6c9100ed932b90ce4500d08ad1f6f21/examples/contactsCreateSingleAndMultiCall.php) I've tried setting up the following request

```
    $campaignsOperation = new GetCampaigns();
    $response = $client->call($campaignsOperation);
    if ($response->isSuccess()) {
        $campaignList = $response->getData();
        $campaign = $campaignList[0];
        /**
         * first lets try to add single contact
         */
        $newContact = new NewContact(
            new CampaignReference($campaign['campaignId']),
            $email,
            new NewContactTag('test'),
        );
        $newContact->setName('SomeName');
        error_log(__METHOD__.": tags = ".print_r($newContact, true));
        $createContact = new CreateContact($newContact);

        $response = $client->call($createContact);
        error_log(__METHOD__.": result = ".print_r($response, true));
        /**
         * note the error handling is omitted, please implement any
         */

    }
```

This returns a 202 response and the new contact is created, but there is no tag assigned. The NewContact object looks like this when it is sent:
```
[name:Getresponse\Sdk\Operation\Model\NewContact:private] => SomeName
    [campaign:Getresponse\Sdk\Operation\Model\NewContact:private] => Getresponse\Sdk\Operation\Model\CampaignReference Object
        (
            [campaignId:Getresponse\Sdk\Operation\Model\CampaignReference:private] => 0
        )

    [email:Getresponse\Sdk\Operation\Model\NewContact:private] => something@gmail.com
    [dayOfCycle:Getresponse\Sdk\Operation\Model\NewContact:private] => field_not_set
    [note:Getresponse\Sdk\Operation\Model\NewContact:private] => field_not_set
    [scoring:Getresponse\Sdk\Operation\Model\NewContact:private] => field_not_set
    [ipAddress:Getresponse\Sdk\Operation\Model\NewContact:private] => field_not_set
    [tags:Getresponse\Sdk\Operation\Model\NewContact:private] => field_not_set
    [customFieldValues:Getresponse\Sdk\Operation\Model\NewContact:private] => field_not_set
```
So the tag attribute is clearly not being included. It would be helpful if the documentation/examples were updated to better illustrate including a tag (or tags) with a new contact request.

**Comment by maciejtarnowski** [comment]
Thanks for the feedback, @templeman ! We'll try to add some more complex examples with more fields set.

In your case, you are trying to pass `NewContactTag` object via `NewContact`'s constructor and it's not possible. You would need to call `setTags` method on `NewContact` object like that:
```php
$newContact = new NewContact(
    new CampaignReference($campaign['campaignId']),
    $email
);
$newContact->setName('SomeName');
$newContact->setTags([new NewContactTag('test')]);
```
Please bear in mind that `test` passed to the `NewContactTag`'s constructor is an identifier, not a name and to get the ID you need to call this API method: [GET /tags](https://apireference.getresponse.com/#operation/getTagsList)

You can find more methods like `setTags` in the source code of `NewContact` class: [src/Operation/Model/NewContact.php](https://github.com/GetResponse/sdk-php/blob/master/src/Operation/Model/NewContact.php).

As a side note - if you're thinking about using that in production, you probably don't want to pull `campaignId` and `tagId` values from the API on every request, but store it in your configuration or some kind of cache. Otherwise, your requests will get throttled quickly.

**Comment by templeman** [comment]
Thank you @maciejtarnowski, your example helped me get on the right track. Here's the request that I have working now
```
    // search for list, use the first one we find
    $campaignsOperation = new GetCampaigns();

    $responseCampaigns = $client->call($campaignsOperation);
    if ($responseCampaigns->isSuccess()) {
        $campaignList = $responseCampaigns->getData();
    }

    // define tag search query
    $getTagsOperation = new GetTags();
    $searchQuery = new GetTagsSearchQuery();
    $searchQuery->whereName('test');
    $getTagsOperation->setQuery($searchQuery);

    $responseTags = $client->call($getTagsOperation);
    if ($responseTags->isSuccess()) {
        $tag = $responseTags->getData();
    }

    if ($campaignList && $tag) {
        $campaign = $campaignList[0];
        // add single contact
        $newContact = new NewContact(
            new CampaignReference($campaign['campaignId']),
            $email
        );
        $newContact->setName('Barack');
        $newContact->setTags([new NewContactTag($tag[0]['tagId'])]);
        $createContact = new CreateContact($newContact);
        $response = $client->call($createContact);

    }
```

Now I also understand that I can use the ID directly if I already have it, so if my tag ID is `hi` I could simply do `$newContact->setTags([new NewContactTag('hi')]);`

**Comment by maciejtarnowski** [comment]
Yes, both campaign ID and tag ID won't change, so once you get them, either via script or using a tool like Postman, you can safely save them in your config and use in future requests.

**Comment by maciej-laskowski** [comment]
@templeman Thank you for this example, it fitted my use case almost perfectly :)

**Comment by maciejtarnowski** [comment]
@templeman I've added an example with full set of contact data in #10, so I'm closing this issue. Let me know if you have additional feedback :)
