### ISSUE TITLE
Hey how to install in Laravel 5?

### ISSUE THREAD

**Issue by CarlangasGO** [GetResponse/sdk-php#7]
in composer.json in laravel added

```

"require": {
 "getresponse/sdk-php-client": "^1.0"
}
```

composer update

Class 'GetresponseClientFactory' not found

**Comment by maciejtarnowski** [comment]
Hello @CarlangasGO,

You need to require this package (`getresponse/sdk-php`), not `getresponse/sdk-php-client`.

To do that, place in your `composer.json` file the following:
```json
{
    "require": {
        "getresponse/sdk-php": "^1.2"
    }
}
```
and run `composer update`.
