### ISSUE TITLE
I don't understand how to send a newsletter

### ISSUE THREAD

**Issue by CarlangasGO** [GetResponse/sdk-php#8]
Hello and thanks for answering

In https://github.com/GetResponse/sdk-php/blob/master/examples/newsletterCreate.php
```

$client = GetresponseClientFactory::createWithApiKey("api");
    
    $createNewsletterContent = new MessageContent();
    $createNewsletterContent->setPlain(uniqid('APIv3 PHP SDK test content - ', true));
    /**
     * note the IDs are example only. You should use your own - obtained from our API or
     * from your local storage.
     * Please avoid unnecessary API calls. For example get a list of FromFields once and store
     * or cache in your system. Repeating unnecessary API calls can lead to additional restrictions and limits.
     */
    $createNewsletterSendSettings = new NewsletterSendSettings();
    $createNewsletterSendSettings->setSelectedContacts(array('exampleContactID'));
    $createNewsletter = new NewNewsletter(
        uniqid('APIv3 PHP SDK test - ', true),
        new FromFieldReference('exampleFFRid'),
        new CampaignReference('8oXvn'),
        $createNewsletterContent,
        $createNewsletterSendSettings
    );
    $createNewsletterOperation = new CreateNewsletter($createNewsletter);
  
```

So I need to select the contact if I am going to send the newsletter to a list that contains several contacts

`$createNewsletterSendSettings->setSelectedContacts(array('exampleContactID'));     
`

how do i get exampleFFRid ?

`new FromFieldReference('exampleFFRid')`

Thanks for your time

**Comment by maciejtarnowski** [comment]
Hi @CarlangasGO,

`FFRid` refers to "From Field ID" that you can get by calling `GET /from-fields` method (`fromFieldId` field). The method's documentation is here: https://apireference.getresponse.com/#operation/getFromFieldList

You might also find `POST /newsletters` docs useful: https://apireference.getresponse.com/#operation/createNewsletter
Providing a list of contacts is only one of the options. It's also possible to select campaigns or segments (saved contact searches) as newsletter recipients.

**Comment by maciejtarnowski** [comment]
I'm closing the issue for now, please let me know if you need any more info and I'll be happy to reopen it for you.
