### ISSUE TITLE
Will you cover CustomEvents for Workflow API?

### ISSUE THREAD

**Issue by oddtwelve** [GetResponse/sdk-php#9]
Will you cover CustomEvents for Workflow API?

**Comment by maciejtarnowski** [comment]
Hi @oddtwelve,

Yes, we will, new SDK version should be released within a few weeks.

**Comment by maciejtarnowski** [comment]
Hi @oddtwelve,

It took a while, but finally Custom Events are available as part of the 2.0.0 SDK release. I hope they'll cover all of your usecases.
Please let us know if you have any feedback about Custom Events operations or the SDK in general by creating a new issue :)

Thanks!
